export enum QUERY_KEYS {
  GET_ALL_CATEGORY = "getAllCategory",
  GET_ONE_CATEGORY = "getOneCategory",
  GET_ONE_PRODUCT = "getOneProduct",
  CART = 'cart',
  ADMIN = 'admin',
  ALL_ORDERS = 'allOrders',
  ALL_PRODUCTS = 'allProducts',
  ALL_USERS = 'allUsers',
  COUPON = 'coupon',
  DISCOUNT_COUPONS = 'discountCoupons',
  MOST_POPULAR_PRODUCTS = 'mostPopularProducts',
  SEARCH_ORDER = 'searchOrder',
  SEARCH = 'search',
  MY_ORDERS = 'myOrders',
  UID = 'uId',
  GET_SALE_EVENT = 'getSaleEvent',
  REVIEW_PRODUCT = 'reviewProduct',
  OVERALL_REVIEW = 'overallReview',
  MY_REVIEW = 'myReviews',
}
